gh api graphql -f query='
            query($organization: String! $proj_num: Int!) {
              organization(login: $organization) {
                projectV2(number: $proj_num) {
                  id
                  items {
                    nodes {
                      id
                      content {
                        ... on Issue {
                          title
                          number
                        }
                      }
                      fieldValues(first: 30) {
                        nodes {
                          ... on ProjectV2ItemFieldPullRequestValue {
                            pullRequests(last: 1) {
                              nodes {
                                id
                                reviews(last: 20) {
                                  nodes {
                                    author {
                                      login
                                    }
                                    state
                                    createdAt
                                  }
                                }
                              }
                            }
                            field {
                              ... on ProjectV2Field {
                                id
                                name
                              }
                            }
                          }
                          ... on ProjectV2ItemFieldSingleSelectValue {
                            id
                            optionId
                            field {
                              ... on ProjectV2SingleSelectField {
                                id
                                name
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }' -f organization=${{env.ORGANIZATION}} -F proj_num=${{env.PROJECT_NUMBER}} > items_data.json
          
          PM_ITEM_ID='"PVTI_lADOC2jf2s4A2aRCzgZTfSc"'
          PM_ITEM=$(jq '.data.organization.projectV2.items.nodes[] | select(.id== '$PM_ITEM_ID) | .' items_data.json)
          approved_by_peers=$( '[.fieldValues.nodes[] | select(.pullRequests?.nodes? != null) | .pullRequests.nodes[] | .reviews.nodes[] | select(.state == "APPROVED")] | length' $PM_ITEM)
         # approved_by_maint=$(jq '.[] | select(.login== "evanpelle" && .state=="approved") | .' items_data.json)
          
          echo "PM_ITEM=$PM_ITEM" >> $GITHUB_ENV
          echo "APPROVED_BY_PEERS=$approved_by_peers" >> $GITHUB_ENV
          echo "APPROVED_BY_MAINT=$approved_by_maint" >> $GITHUB_ENV
